import { useEffect, useState, type ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowLeft, Printer } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useRegister } from "@/lib/register-store";
import { useCurrentUser } from "@/lib/auth-store";

// Shared chrome for every /report-* page: back link, title, and the print-only heading
// used when printing (see .report-print-area in styles.css). `download` comes from the
// route's `?download=1` search param — set when arriving here from the Inbox
// notification's printable-report link — and auto-opens the print dialog on mount.
//
// Auto-opening print() in a freshly-opened tab is unreliable across browsers (some
// suppress it if the tab isn't focused yet, or if it fires before the tab has full user
// activation) — so this both attempts it automatically AND shows a manual fallback
// button, rather than leaving "nothing happened" as the only outcome when the browser
// blocks the automatic attempt.
export function ReportPageShell({
  title,
  description,
  download,
  extraHeader,
  children,
}: {
  title: string;
  description: string;
  download?: boolean;
  extraHeader?: ReactNode;
  children: ReactNode;
}) {
  const { storeName } = useRegister();
  const user = useCurrentUser();
  // Captured once per page load rather than kept live, so the "generated at" stamp on a
  // printed/PDF copy reflects the moment the report was opened, not whenever it was printed.
  const [generatedAt] = useState(() => new Date().toLocaleString());

  useEffect(() => {
    if (!download) return;
    toast.success(`Preparing ${title} — opening print dialog...`, {
      description: 'If nothing opens automatically, use the "Open Print Dialog" button.',
    });
    const id = setTimeout(() => {
      window.focus();
      window.print();
    }, 500);
    return () => clearTimeout(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [download]);

  return (
    <AppShell>
      <div className="flex flex-col gap-4 p-4 md:p-6">
        <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
          <div>
            <Link
              to="/reports"
              className="mb-1 flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="h-3.5 w-3.5" /> Back to Reports
            </Link>
            <h1 className="text-2xl font-bold text-foreground">{title}</h1>
            <p className="text-sm text-muted-foreground">{description}</p>
          </div>
          <div className="flex items-end gap-2">
            {extraHeader}
            <Button variant="outline" onClick={() => window.print()} className="gap-1.5">
              <Printer className="h-4 w-4" /> Download PDF
            </Button>
          </div>
        </div>

        <div className="report-print-area flex flex-col gap-4">
          <div className="hidden print:block">
            <p className="text-lg font-bold text-black">{title}</p>
          </div>
          <div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-1 text-xs text-muted-foreground print:text-black">
            <span className="font-medium">{storeName}</span>
            <span>
              Generated by {user?.name ?? "Unknown"} on {generatedAt}
            </span>
          </div>
          {children}
        </div>
      </div>
    </AppShell>
  );
}

// TanStack Router's default search parser JSON-parses query values, so `?download=1`
// arrives here as the number 1 (not the string "1") — accept anything truthy rather than
// matching one specific type/value.
export const downloadSearchSchema = (search: Record<string, unknown>): { download?: boolean } => ({
  download: search.download ? true : undefined,
});

export function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <Card className="p-4">
      <p className="text-xs uppercase text-muted-foreground">{label}</p>
      <p className="mt-1 text-xl font-bold text-foreground">{value}</p>
    </Card>
  );
}

export function SummaryRow({
  label,
  value,
  emphasize,
}: {
  label: string;
  value: string;
  emphasize?: boolean;
}) {
  return (
    <div className="flex items-center justify-between border-b border-border/50 pb-2">
      <span className="text-muted-foreground">{label}</span>
      <span className={emphasize ? "font-bold text-foreground" : "font-medium text-foreground"}>
        {value}
      </span>
    </div>
  );
}
