/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockCountRouteImport } from './routes/stock-count'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportStockMovementRouteImport } from './routes/report-stock-movement'
import { Route as ReportStockRouteImport } from './routes/report-stock'
import { Route as ReportSalesVoidRouteImport } from './routes/report-sales-void'
import { Route as ReportReorderRouteImport } from './routes/report-reorder'
import { Route as ReportProductSalesRouteImport } from './routes/report-product-sales'
import { Route as ReportPeriodSalesRouteImport } from './routes/report-period-sales'
import { Route as ReportOutstandingBillsRouteImport } from './routes/report-outstanding-bills'
import { Route as ReportGstReturnRouteImport } from './routes/report-gst-return'
import { Route as ReportFocBillsRouteImport } from './routes/report-foc-bills'
import { Route as ReportDaySummaryRouteImport } from './routes/report-day-summary'
import { Route as ReportCustomerSalesRouteImport } from './routes/report-customer-sales'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryItemsRouteImport } from './routes/inventory-items'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplyHomeRouteImport } from './routes/supply.home'
import { Route as PosSellRouteImport } from './routes/pos.sell'
import { Route as PosRegisterSessionsRouteImport } from './routes/pos.register-sessions'
import { Route as PosRegisterRouteImport } from './routes/pos.register'
import { Route as PosQuotationsRouteImport } from './routes/pos.quotations'
import { Route as PosOnlinePaymentsRouteImport } from './routes/pos.online-payments'
import { Route as PosBillHistoryRouteImport } from './routes/pos.bill-history'
import { Route as MyDhiposCustomerIdRouteImport } from './routes/my-dhipos.$customerId'
import { Route as EBillNumberRouteImport } from './routes/e-bill.$number'
import { Route as AnalyticsSalesRouteImport } from './routes/analytics.sales'
import { Route as AnalyticsInventoryRouteImport } from './routes/analytics.inventory'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTaxesRouteImport } from './routes/admin.taxes'
import { Route as AdminSuperAdminRouteImport } from './routes/admin.super-admin'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPrintTemplatesRouteImport } from './routes/admin.print-templates'
import { Route as AdminNotificationRouteImport } from './routes/admin.notification'
import { Route as AdminLoyaltyProgramsRouteImport } from './routes/admin.loyalty-programs'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'

const StockCountRoute = StockCountRouteImport.update({
  id: '/stock-count',
  path: '/stock-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportStockMovementRoute = ReportStockMovementRouteImport.update({
  id: '/report-stock-movement',
  path: '/report-stock-movement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportStockRoute = ReportStockRouteImport.update({
  id: '/report-stock',
  path: '/report-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSalesVoidRoute = ReportSalesVoidRouteImport.update({
  id: '/report-sales-void',
  path: '/report-sales-void',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReorderRoute = ReportReorderRouteImport.update({
  id: '/report-reorder',
  path: '/report-reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportProductSalesRoute = ReportProductSalesRouteImport.update({
  id: '/report-product-sales',
  path: '/report-product-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportPeriodSalesRoute = ReportPeriodSalesRouteImport.update({
  id: '/report-period-sales',
  path: '/report-period-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportOutstandingBillsRoute = ReportOutstandingBillsRouteImport.update({
  id: '/report-outstanding-bills',
  path: '/report-outstanding-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportGstReturnRoute = ReportGstReturnRouteImport.update({
  id: '/report-gst-return',
  path: '/report-gst-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFocBillsRoute = ReportFocBillsRouteImport.update({
  id: '/report-foc-bills',
  path: '/report-foc-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportDaySummaryRoute = ReportDaySummaryRouteImport.update({
  id: '/report-day-summary',
  path: '/report-day-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCustomerSalesRoute = ReportCustomerSalesRouteImport.update({
  id: '/report-customer-sales',
  path: '/report-customer-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory-items',
  path: '/inventory-items',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyHomeRoute = SupplyHomeRouteImport.update({
  id: '/supply/home',
  path: '/supply/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PosSellRoute = PosSellRouteImport.update({
  id: '/pos/sell',
  path: '/pos/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRegisterSessionsRoute = PosRegisterSessionsRouteImport.update({
  id: '/pos/register-sessions',
  path: '/pos/register-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRegisterRoute = PosRegisterRouteImport.update({
  id: '/pos/register',
  path: '/pos/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PosQuotationsRoute = PosQuotationsRouteImport.update({
  id: '/pos/quotations',
  path: '/pos/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PosOnlinePaymentsRoute = PosOnlinePaymentsRouteImport.update({
  id: '/pos/online-payments',
  path: '/pos/online-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PosBillHistoryRoute = PosBillHistoryRouteImport.update({
  id: '/pos/bill-history',
  path: '/pos/bill-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDhiposCustomerIdRoute = MyDhiposCustomerIdRouteImport.update({
  id: '/my-dhipos/$customerId',
  path: '/my-dhipos/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const EBillNumberRoute = EBillNumberRouteImport.update({
  id: '/e-bill/$number',
  path: '/e-bill/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsSalesRoute = AnalyticsSalesRouteImport.update({
  id: '/analytics/sales',
  path: '/analytics/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsInventoryRoute = AnalyticsInventoryRouteImport.update({
  id: '/analytics/inventory',
  path: '/analytics/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTaxesRoute = AdminTaxesRouteImport.update({
  id: '/admin/taxes',
  path: '/admin/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuperAdminRoute = AdminSuperAdminRouteImport.update({
  id: '/admin/super-admin',
  path: '/admin/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrintTemplatesRoute = AdminPrintTemplatesRouteImport.update({
  id: '/admin/print-templates',
  path: '/admin/print-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationRoute = AdminNotificationRouteImport.update({
  id: '/admin/notification',
  path: '/admin/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoyaltyProgramsRoute = AdminLoyaltyProgramsRouteImport.update({
  id: '/admin/loyalty-programs',
  path: '/admin/loyalty-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/inventory-items': typeof InventoryItemsRoute
  '/login': typeof LoginRoute
  '/my-profile': typeof MyProfileRoute
  '/products': typeof ProductsRoute
  '/report-customer-sales': typeof ReportCustomerSalesRoute
  '/report-day-summary': typeof ReportDaySummaryRoute
  '/report-foc-bills': typeof ReportFocBillsRoute
  '/report-gst-return': typeof ReportGstReturnRoute
  '/report-outstanding-bills': typeof ReportOutstandingBillsRoute
  '/report-period-sales': typeof ReportPeriodSalesRoute
  '/report-product-sales': typeof ReportProductSalesRoute
  '/report-reorder': typeof ReportReorderRoute
  '/report-sales-void': typeof ReportSalesVoidRoute
  '/report-stock': typeof ReportStockRoute
  '/report-stock-movement': typeof ReportStockMovementRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock-count': typeof StockCountRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/loyalty-programs': typeof AdminLoyaltyProgramsRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/print-templates': typeof AdminPrintTemplatesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/inventory': typeof AnalyticsInventoryRoute
  '/analytics/sales': typeof AnalyticsSalesRoute
  '/e-bill/$number': typeof EBillNumberRoute
  '/my-dhipos/$customerId': typeof MyDhiposCustomerIdRoute
  '/pos/bill-history': typeof PosBillHistoryRoute
  '/pos/online-payments': typeof PosOnlinePaymentsRoute
  '/pos/quotations': typeof PosQuotationsRoute
  '/pos/register': typeof PosRegisterRoute
  '/pos/register-sessions': typeof PosRegisterSessionsRoute
  '/pos/sell': typeof PosSellRoute
  '/supply/home': typeof SupplyHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/inventory-items': typeof InventoryItemsRoute
  '/login': typeof LoginRoute
  '/my-profile': typeof MyProfileRoute
  '/products': typeof ProductsRoute
  '/report-customer-sales': typeof ReportCustomerSalesRoute
  '/report-day-summary': typeof ReportDaySummaryRoute
  '/report-foc-bills': typeof ReportFocBillsRoute
  '/report-gst-return': typeof ReportGstReturnRoute
  '/report-outstanding-bills': typeof ReportOutstandingBillsRoute
  '/report-period-sales': typeof ReportPeriodSalesRoute
  '/report-product-sales': typeof ReportProductSalesRoute
  '/report-reorder': typeof ReportReorderRoute
  '/report-sales-void': typeof ReportSalesVoidRoute
  '/report-stock': typeof ReportStockRoute
  '/report-stock-movement': typeof ReportStockMovementRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock-count': typeof StockCountRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/loyalty-programs': typeof AdminLoyaltyProgramsRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/print-templates': typeof AdminPrintTemplatesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/inventory': typeof AnalyticsInventoryRoute
  '/analytics/sales': typeof AnalyticsSalesRoute
  '/e-bill/$number': typeof EBillNumberRoute
  '/my-dhipos/$customerId': typeof MyDhiposCustomerIdRoute
  '/pos/bill-history': typeof PosBillHistoryRoute
  '/pos/online-payments': typeof PosOnlinePaymentsRoute
  '/pos/quotations': typeof PosQuotationsRoute
  '/pos/register': typeof PosRegisterRoute
  '/pos/register-sessions': typeof PosRegisterSessionsRoute
  '/pos/sell': typeof PosSellRoute
  '/supply/home': typeof SupplyHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/inventory-items': typeof InventoryItemsRoute
  '/login': typeof LoginRoute
  '/my-profile': typeof MyProfileRoute
  '/products': typeof ProductsRoute
  '/report-customer-sales': typeof ReportCustomerSalesRoute
  '/report-day-summary': typeof ReportDaySummaryRoute
  '/report-foc-bills': typeof ReportFocBillsRoute
  '/report-gst-return': typeof ReportGstReturnRoute
  '/report-outstanding-bills': typeof ReportOutstandingBillsRoute
  '/report-period-sales': typeof ReportPeriodSalesRoute
  '/report-product-sales': typeof ReportProductSalesRoute
  '/report-reorder': typeof ReportReorderRoute
  '/report-sales-void': typeof ReportSalesVoidRoute
  '/report-stock': typeof ReportStockRoute
  '/report-stock-movement': typeof ReportStockMovementRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock-count': typeof StockCountRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/loyalty-programs': typeof AdminLoyaltyProgramsRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/print-templates': typeof AdminPrintTemplatesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/inventory': typeof AnalyticsInventoryRoute
  '/analytics/sales': typeof AnalyticsSalesRoute
  '/e-bill/$number': typeof EBillNumberRoute
  '/my-dhipos/$customerId': typeof MyDhiposCustomerIdRoute
  '/pos/bill-history': typeof PosBillHistoryRoute
  '/pos/online-payments': typeof PosOnlinePaymentsRoute
  '/pos/quotations': typeof PosQuotationsRoute
  '/pos/register': typeof PosRegisterRoute
  '/pos/register-sessions': typeof PosRegisterSessionsRoute
  '/pos/sell': typeof PosSellRoute
  '/supply/home': typeof SupplyHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/inventory-items'
    | '/login'
    | '/my-profile'
    | '/products'
    | '/report-customer-sales'
    | '/report-day-summary'
    | '/report-foc-bills'
    | '/report-gst-return'
    | '/report-outstanding-bills'
    | '/report-period-sales'
    | '/report-product-sales'
    | '/report-reorder'
    | '/report-sales-void'
    | '/report-stock'
    | '/report-stock-movement'
    | '/reports'
    | '/reset-password'
    | '/stock-count'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/employees'
    | '/admin/integrations'
    | '/admin/locations'
    | '/admin/loyalty-programs'
    | '/admin/notification'
    | '/admin/print-templates'
    | '/admin/settings'
    | '/admin/super-admin'
    | '/admin/taxes'
    | '/admin/users'
    | '/analytics/inventory'
    | '/analytics/sales'
    | '/e-bill/$number'
    | '/my-dhipos/$customerId'
    | '/pos/bill-history'
    | '/pos/online-payments'
    | '/pos/quotations'
    | '/pos/register'
    | '/pos/register-sessions'
    | '/pos/sell'
    | '/supply/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/inventory-items'
    | '/login'
    | '/my-profile'
    | '/products'
    | '/report-customer-sales'
    | '/report-day-summary'
    | '/report-foc-bills'
    | '/report-gst-return'
    | '/report-outstanding-bills'
    | '/report-period-sales'
    | '/report-product-sales'
    | '/report-reorder'
    | '/report-sales-void'
    | '/report-stock'
    | '/report-stock-movement'
    | '/reports'
    | '/reset-password'
    | '/stock-count'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/employees'
    | '/admin/integrations'
    | '/admin/locations'
    | '/admin/loyalty-programs'
    | '/admin/notification'
    | '/admin/print-templates'
    | '/admin/settings'
    | '/admin/super-admin'
    | '/admin/taxes'
    | '/admin/users'
    | '/analytics/inventory'
    | '/analytics/sales'
    | '/e-bill/$number'
    | '/my-dhipos/$customerId'
    | '/pos/bill-history'
    | '/pos/online-payments'
    | '/pos/quotations'
    | '/pos/register'
    | '/pos/register-sessions'
    | '/pos/sell'
    | '/supply/home'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/inventory-items'
    | '/login'
    | '/my-profile'
    | '/products'
    | '/report-customer-sales'
    | '/report-day-summary'
    | '/report-foc-bills'
    | '/report-gst-return'
    | '/report-outstanding-bills'
    | '/report-period-sales'
    | '/report-product-sales'
    | '/report-reorder'
    | '/report-sales-void'
    | '/report-stock'
    | '/report-stock-movement'
    | '/reports'
    | '/reset-password'
    | '/stock-count'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/employees'
    | '/admin/integrations'
    | '/admin/locations'
    | '/admin/loyalty-programs'
    | '/admin/notification'
    | '/admin/print-templates'
    | '/admin/settings'
    | '/admin/super-admin'
    | '/admin/taxes'
    | '/admin/users'
    | '/analytics/inventory'
    | '/analytics/sales'
    | '/e-bill/$number'
    | '/my-dhipos/$customerId'
    | '/pos/bill-history'
    | '/pos/online-payments'
    | '/pos/quotations'
    | '/pos/register'
    | '/pos/register-sessions'
    | '/pos/sell'
    | '/supply/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  LoginRoute: typeof LoginRoute
  MyProfileRoute: typeof MyProfileRoute
  ProductsRoute: typeof ProductsRoute
  ReportCustomerSalesRoute: typeof ReportCustomerSalesRoute
  ReportDaySummaryRoute: typeof ReportDaySummaryRoute
  ReportFocBillsRoute: typeof ReportFocBillsRoute
  ReportGstReturnRoute: typeof ReportGstReturnRoute
  ReportOutstandingBillsRoute: typeof ReportOutstandingBillsRoute
  ReportPeriodSalesRoute: typeof ReportPeriodSalesRoute
  ReportProductSalesRoute: typeof ReportProductSalesRoute
  ReportReorderRoute: typeof ReportReorderRoute
  ReportSalesVoidRoute: typeof ReportSalesVoidRoute
  ReportStockRoute: typeof ReportStockRoute
  ReportStockMovementRoute: typeof ReportStockMovementRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StockCountRoute: typeof StockCountRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminLoyaltyProgramsRoute: typeof AdminLoyaltyProgramsRoute
  AdminNotificationRoute: typeof AdminNotificationRoute
  AdminPrintTemplatesRoute: typeof AdminPrintTemplatesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuperAdminRoute: typeof AdminSuperAdminRoute
  AdminTaxesRoute: typeof AdminTaxesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AnalyticsInventoryRoute: typeof AnalyticsInventoryRoute
  AnalyticsSalesRoute: typeof AnalyticsSalesRoute
  EBillNumberRoute: typeof EBillNumberRoute
  MyDhiposCustomerIdRoute: typeof MyDhiposCustomerIdRoute
  PosBillHistoryRoute: typeof PosBillHistoryRoute
  PosOnlinePaymentsRoute: typeof PosOnlinePaymentsRoute
  PosQuotationsRoute: typeof PosQuotationsRoute
  PosRegisterRoute: typeof PosRegisterRoute
  PosRegisterSessionsRoute: typeof PosRegisterSessionsRoute
  PosSellRoute: typeof PosSellRoute
  SupplyHomeRoute: typeof SupplyHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock-count': {
      id: '/stock-count'
      path: '/stock-count'
      fullPath: '/stock-count'
      preLoaderRoute: typeof StockCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-stock-movement': {
      id: '/report-stock-movement'
      path: '/report-stock-movement'
      fullPath: '/report-stock-movement'
      preLoaderRoute: typeof ReportStockMovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-stock': {
      id: '/report-stock'
      path: '/report-stock'
      fullPath: '/report-stock'
      preLoaderRoute: typeof ReportStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-sales-void': {
      id: '/report-sales-void'
      path: '/report-sales-void'
      fullPath: '/report-sales-void'
      preLoaderRoute: typeof ReportSalesVoidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-reorder': {
      id: '/report-reorder'
      path: '/report-reorder'
      fullPath: '/report-reorder'
      preLoaderRoute: typeof ReportReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-product-sales': {
      id: '/report-product-sales'
      path: '/report-product-sales'
      fullPath: '/report-product-sales'
      preLoaderRoute: typeof ReportProductSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-period-sales': {
      id: '/report-period-sales'
      path: '/report-period-sales'
      fullPath: '/report-period-sales'
      preLoaderRoute: typeof ReportPeriodSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-outstanding-bills': {
      id: '/report-outstanding-bills'
      path: '/report-outstanding-bills'
      fullPath: '/report-outstanding-bills'
      preLoaderRoute: typeof ReportOutstandingBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-gst-return': {
      id: '/report-gst-return'
      path: '/report-gst-return'
      fullPath: '/report-gst-return'
      preLoaderRoute: typeof ReportGstReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-foc-bills': {
      id: '/report-foc-bills'
      path: '/report-foc-bills'
      fullPath: '/report-foc-bills'
      preLoaderRoute: typeof ReportFocBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-day-summary': {
      id: '/report-day-summary'
      path: '/report-day-summary'
      fullPath: '/report-day-summary'
      preLoaderRoute: typeof ReportDaySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-customer-sales': {
      id: '/report-customer-sales'
      path: '/report-customer-sales'
      fullPath: '/report-customer-sales'
      preLoaderRoute: typeof ReportCustomerSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-items': {
      id: '/inventory-items'
      path: '/inventory-items'
      fullPath: '/inventory-items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/home': {
      id: '/supply/home'
      path: '/supply/home'
      fullPath: '/supply/home'
      preLoaderRoute: typeof SupplyHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/sell': {
      id: '/pos/sell'
      path: '/pos/sell'
      fullPath: '/pos/sell'
      preLoaderRoute: typeof PosSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/register-sessions': {
      id: '/pos/register-sessions'
      path: '/pos/register-sessions'
      fullPath: '/pos/register-sessions'
      preLoaderRoute: typeof PosRegisterSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/register': {
      id: '/pos/register'
      path: '/pos/register'
      fullPath: '/pos/register'
      preLoaderRoute: typeof PosRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/quotations': {
      id: '/pos/quotations'
      path: '/pos/quotations'
      fullPath: '/pos/quotations'
      preLoaderRoute: typeof PosQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/online-payments': {
      id: '/pos/online-payments'
      path: '/pos/online-payments'
      fullPath: '/pos/online-payments'
      preLoaderRoute: typeof PosOnlinePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/bill-history': {
      id: '/pos/bill-history'
      path: '/pos/bill-history'
      fullPath: '/pos/bill-history'
      preLoaderRoute: typeof PosBillHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-dhipos/$customerId': {
      id: '/my-dhipos/$customerId'
      path: '/my-dhipos/$customerId'
      fullPath: '/my-dhipos/$customerId'
      preLoaderRoute: typeof MyDhiposCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-bill/$number': {
      id: '/e-bill/$number'
      path: '/e-bill/$number'
      fullPath: '/e-bill/$number'
      preLoaderRoute: typeof EBillNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/sales': {
      id: '/analytics/sales'
      path: '/analytics/sales'
      fullPath: '/analytics/sales'
      preLoaderRoute: typeof AnalyticsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/inventory': {
      id: '/analytics/inventory'
      path: '/analytics/inventory'
      fullPath: '/analytics/inventory'
      preLoaderRoute: typeof AnalyticsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/taxes': {
      id: '/admin/taxes'
      path: '/admin/taxes'
      fullPath: '/admin/taxes'
      preLoaderRoute: typeof AdminTaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/super-admin': {
      id: '/admin/super-admin'
      path: '/admin/super-admin'
      fullPath: '/admin/super-admin'
      preLoaderRoute: typeof AdminSuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/print-templates': {
      id: '/admin/print-templates'
      path: '/admin/print-templates'
      fullPath: '/admin/print-templates'
      preLoaderRoute: typeof AdminPrintTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notification': {
      id: '/admin/notification'
      path: '/admin/notification'
      fullPath: '/admin/notification'
      preLoaderRoute: typeof AdminNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loyalty-programs': {
      id: '/admin/loyalty-programs'
      path: '/admin/loyalty-programs'
      fullPath: '/admin/loyalty-programs'
      preLoaderRoute: typeof AdminLoyaltyProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  LoginRoute: LoginRoute,
  MyProfileRoute: MyProfileRoute,
  ProductsRoute: ProductsRoute,
  ReportCustomerSalesRoute: ReportCustomerSalesRoute,
  ReportDaySummaryRoute: ReportDaySummaryRoute,
  ReportFocBillsRoute: ReportFocBillsRoute,
  ReportGstReturnRoute: ReportGstReturnRoute,
  ReportOutstandingBillsRoute: ReportOutstandingBillsRoute,
  ReportPeriodSalesRoute: ReportPeriodSalesRoute,
  ReportProductSalesRoute: ReportProductSalesRoute,
  ReportReorderRoute: ReportReorderRoute,
  ReportSalesVoidRoute: ReportSalesVoidRoute,
  ReportStockRoute: ReportStockRoute,
  ReportStockMovementRoute: ReportStockMovementRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StockCountRoute: StockCountRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminLoyaltyProgramsRoute: AdminLoyaltyProgramsRoute,
  AdminNotificationRoute: AdminNotificationRoute,
  AdminPrintTemplatesRoute: AdminPrintTemplatesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuperAdminRoute: AdminSuperAdminRoute,
  AdminTaxesRoute: AdminTaxesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AnalyticsInventoryRoute: AnalyticsInventoryRoute,
  AnalyticsSalesRoute: AnalyticsSalesRoute,
  EBillNumberRoute: EBillNumberRoute,
  MyDhiposCustomerIdRoute: MyDhiposCustomerIdRoute,
  PosBillHistoryRoute: PosBillHistoryRoute,
  PosOnlinePaymentsRoute: PosOnlinePaymentsRoute,
  PosQuotationsRoute: PosQuotationsRoute,
  PosRegisterRoute: PosRegisterRoute,
  PosRegisterSessionsRoute: PosRegisterSessionsRoute,
  PosSellRoute: PosSellRoute,
  SupplyHomeRoute: SupplyHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
